import {
  fossInfoLinks,
  getLaunchCtaConfig,
  githubRepositoryUrl,
  localOnlyBoundarySummary,
  localOnlyDataSummary,
  siteMetadataDescription
} from '../lib/site-policy';
import { createPublicPageMetadata } from '../lib/site-metadata';

export const metadata = createPublicPageMetadata({
  pathname: '/',
  title: 'PageMint - Save any page as a local PDF',
  description: siteMetadataDescription
});

function CornerMarks(): React.ReactNode {
  return (
    <>
      <span className="cornerMark cornerMark--tl" aria-hidden="true" />
      <span className="cornerMark cornerMark--tr" aria-hidden="true" />
      <span className="cornerMark cornerMark--bl" aria-hidden="true" />
      <span className="cornerMark cornerMark--br" aria-hidden="true" />
    </>
  );
}

function OrnamentRule(): React.ReactNode {
  return <hr className="ornamentRule" />;
}

export default function HomePage(): React.ReactNode {
  const launchCta = getLaunchCtaConfig();

  return (
    <main>
      <div className="hero">
        <section className="panel heroPanel">
          <CornerMarks />

          <div className="heroMasthead">
            <p className="eyebrow heroEyebrow">PageMint · MIT FOSS</p>
            <h1 className="heroH1">
              Save any page<br />
              as a <em>PDF.</em><br />
              <em className="heroH1Locally">Locally.</em>
            </h1>
          </div>

          <div className="heroBody">
            <p className="lead heroLead">
              Save web pages, including authenticated pages, as local PDFs. PageMint is free, open source, and built so page content never leaves the browser.
            </p>
            <div className="heroCtas">
              {launchCta.external ? (
                <a className="btn btn--primary btn--lg" href={launchCta.href} rel="noreferrer">
                  {launchCta.label}
                  <span className="btn-arrow" aria-hidden="true">→</span>
                </a>
              ) : (
                <a className="btn btn--primary btn--lg" href={launchCta.href}>
                  {launchCta.label}
                  <span className="btn-arrow" aria-hidden="true">→</span>
                </a>
              )}
              <a className="btn btn--ghost" href={githubRepositoryUrl} rel="noreferrer">
                View source
                <span className="btn-arrow" aria-hidden="true">→</span>
              </a>
            </div>
          </div>

          <div className="heroPopupCard" aria-hidden="true">
            <div className="demoPopup">
              <div className="demoPopupHead">
                <span className="demoPopupMark">
                  <span className="demoPopupMarkP">P</span>
                  <span className="demoPopupMarkName">ageMint</span>
                  <span className="demoPopupMarkDot" />
                </span>
                <div className="demoPopupHeadActions">
                  <span className="demoPopupHfBadge">HF</span>
                </div>
              </div>
              <h3 className="demoPopupTitle">Save a high-fidelity PDF</h3>
              <div className="demoPopupScopeRow">
                <span className="demoPopupScopeLabel">Capture</span>
                <span className="demoPopupSelect">Whole page</span>
              </div>
              <div className="demoPopupActionRow">
                <button className="demoPopupSaveBtn" type="button" tabIndex={-1}>
                  <span className="demoPopupSaveIcon" aria-hidden="true">↓</span>
                  Save as PDF
                </button>
              </div>
              <button className="demoPopupSecondaryBtn" type="button" tabIndex={-1}>Remove elements on page</button>
              <span className="demoPopupSettingsLink">Settings</span>
            </div>
          </div>
        </section>

        <OrnamentRule />

        <section className="panel sectionPanel demoVideoPanel" id="see-it">
          <CornerMarks />
          <div className="sectionHeading">
            <p className="eyebrow eyebrow--mint">See it in action</p>
            <h2>One click. <em>Trustworthy</em> PDF.</h2>
          </div>
          <figure className="demoVideoFrame">
            <span className="demoVideoTag">pagemint · live capture</span>
            {/* Generated by apps/demo-video - regenerate with
                `pnpm --filter @pagemint/demo-video build:and:publish` */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              className="demoVideoMedia"
              src="/demo/pagemint-demo.gif"
              alt="PageMint browser extension capturing a web page and rendering it to a local PDF."
              loading="lazy"
              decoding="async"
            />
          </figure>
        </section>

        <section className="panel sectionPanel">
          <CornerMarks />
          <div className="sectionHeading">
            <p className="eyebrow eyebrow--mint">Local boundary</p>
            <h2>No hosted data backend in the product path.</h2>
          </div>
          <div className="stackList">
            <div className="callout">
              <span aria-hidden="true">✓</span>
              <p>{localOnlyDataSummary}</p>
            </div>
            <div className="callout">
              <span aria-hidden="true">✓</span>
              <p>{localOnlyBoundarySummary}</p>
            </div>
          </div>
        </section>

        <section className="panel sectionPanel">
          <CornerMarks />
          <div className="sectionHeading">
            <p className="eyebrow">Project</p>
            <h2>Open by default.</h2>
          </div>
          <div className="grid cardGrid">
            {fossInfoLinks.map((item) => (
              <article className="panel nestedPanel" key={item.href}>
                <p className="eyebrow">{item.title}</p>
                <p>{item.body}</p>
                <a className="textLink" href={item.href} rel="noreferrer">{item.cta}</a>
              </article>
            ))}
          </div>
        </section>
      </div>
    </main>
  );
}
